/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment;

public class App {


    public static void main(String[] args) {
        long startTime = System.currentTimeMillis();
        if(UserInput.isValidUserInput(args)) {
            LogFile currentLogFile = new LogFile(args);
            currentLogFile.processFile();
        }
        long endTime = System.currentTimeMillis();
        System.out.println("The program ran " + (endTime - startTime) + " ms.");
    }

}
